mariadb:
  image: livingstoneonline/mariadb
  container_name: mariadb
  env_file: env/mariadb.env

tomcat:
  image: livingstoneonline/fedora-sample-data
  container_name: tomcat
  env_file: env/tomcat.env
  ports:
    - "8080:8080"
  links:
    - mariadb:mysql

drupal:
  image: livingstoneonline/livingstone
  container_name: drupal
  env_file: env/drupal.env
  ports:
    - "80:80"
  links:
    - mariadb:mysql
    - tomcat:fedora
