version: "3.2"
volumes:
  var-log:
  tomcat-log:
  tomcat-tmp:
  fedora-tmp:
  mysql-files:
  drupal-tmp:
services:
  livingstone:
    image: livingstoneonline/livingstone:prod
    container_name: livingstone
    restart: always
    env_file: docker.env
    environment:
      - DRUPAL_SITE_DB_REPLACE_EXISTING=no
      - DRUPAL_SITE_DB_IMPORT=no
      - DRUPAL_SITE_FEATURES_ENABLE=no
      - DRUPAL_IMPORT_DATA=no
    depends_on:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      # Import files.
      - "./assets:/assets"
      # User uploaded content.
      - "/data/drupal:/var/www/localhost/htdocs/sites/default/files"
      # Preserve temp files used between start and stopping of the server.
      - "drupal-tmp:/tmp"
      # Apache logs
      - "var-log:/var/log"
      # Fedora data read when calculating the space used for display in the
      # Fedora import page.
      - "/data/fedora:/opt/fedora/data"
      # MySQL files is used to import CSV files into the database quickly.
      - "mysql-files:/var/lib/mysql-files"
    ports:
      - "80:80"
  tomcat:
    image: livingstoneonline/tomcat
    container_name: tomcat
    restart: always
    env_file: docker.env
    environment:
      - FEDORA_IMPORT_DATA=no
      - FEDORA_REBUILD=no
      - SOLR_IMPORT_DATA=no
      - SOLR_REBUILD=no
    depends_on:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "tomcat-log:/opt/tomcat/logs"
      - "tomcat-tmp:/opt/tomcat/temp"
      - "fedora-tmp:/opt/fedora/server/management/upload"
      - "/data/fedora:/opt/fedora/data"
      - "/data/solr:/opt/solr/collection1/data"
      - "/data/drupal-solr:/opt/solr/drupal/data"
    ports:
      - "8080:8080"
  mysql:
    image: livingstoneonline/mysql
    container_name: mysql
    restart: always
    env_file: docker.env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "/data/mysql:/var/lib/mysql"
      - "mysql-files:/var/lib/mysql-files"
    ports:
      - "3306:3306"
