version: "2"
volumes:
  - "fedora:/opt/fedora/data"
  - "fedora-tmp:/opt/fedora/server/management/upload"
  - "solr:/opt/solr/collection1/data"
  - "mysql:/var/lib/mysql"
  - "drupal:/var/www/html/sites/default/files"
services:
  livingstone:
    image: livingstoneonline/livingstone:dev
    container_name: livingstone
    env_file: docker.env
    build:
      context: ./images/livingstone
      dockerfile: ./images/livingstone/Dockerfile.dev
    environment:
      - DRUPAL_SITE_DB_REPLACE_EXISTING=no
      - DRUPAL_SITE_DB_IMPORT=yes
      - FEDORA_IMPORT_DATA=yes
      - FEDORA_REBUILD=no
    volumes:
      - "./assets/dev:/assets"
      - "./code/livingstone_online_features:/var/www/html/sites/all/features"
      - "./code/livingstone_online_theme:/var/www/html/sites/all/themes/lo"
      - "fedora"
      - "fedora-temp"
      - "solr"
      - "mysql"
      - "drupal"
    ports:
      - "80:80"
      - "8080:8080"
      - "3306:3306"
