version: "2"
volumes:
  fedora-tmp:
  tomcat-tmp:
  tomcat-log:
  var-log:
  tmp:
services:
  livingstone:
    image: livingstoneonline/livingstone:prod
    container_name: livingstone
    restart: always
    env_file: docker.env
    environment:
      - DRUPAL_SITE_DB_REPLACE_EXISTING=no
      - DRUPAL_DB_IMPORT=no
      - FEDORA_IMPORT_DATA=no
      - FEDORA_REBUILD=no
      - ENABLE_CRON=yes
    volumes:
      - "tomcat-log:/opt/tomcat/logs"
      - "tomcat-tmp:/opt/tomcat/temp"
      - "fedora-tmp:/opt/fedora/server/management/upload"
      - "var-log:/var/log"
      - "tmp:/tmp"
      - "/data/mysql:/var/lib/mysql"
      - "/data/fedora:/opt/fedora/data"
      - "/data/solr:/opt/solr/collection1/data"
      - "/data/drupal:/var/www/html/sites/default/files"
      - "/data/drupal-solr:/opt/solr/drupal/data"
      - "./assets/prod:/assets"
    ports:
      - "80:80"
