#!/bin/bash

readonly ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
readonly NAMESPACE=livingstoneonline
readonly OPTS="$@"

build_dependancy() {
  local image=$1
  local tag=$2
  local context=$ROOT/images/${3:-$image}
  local name=$NAMESPACE/$image
  local build=
  if [ -n "$tag" ]; then
      name="$name:$tag"
      build="--build-arg BUILD_ENVIRONMENT=${tag}"
  fi
  echo docker build $build -t $name $context
  docker build $build -t $name $context
}

build_ubuntu_base_images() {
  build_dependancy base ubuntu base-ubuntu
  build_dependancy ftp &
  build_dependancy oracle-jdk &
  wait
  build_dependancy tomcat &
}

build_alpine_base_images() {
  build_dependancy base alpine base-alpine
  build_dependancy mysql &
  build_dependancy drupal &
  wait
  build_dependancy livingstone ${1:-dev}
}

main() {
  if hash docker-machine 2>/dev/null; then
      eval $(docker-machine env default)
  fi
  # Dependencies
  build_dependancy auto-deploy &
  build_ubuntu_base_images &
  build_alpine_base_images &
}
main "$@"
