#!/bin/bash

readonly ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

$ROOT/commands/remove-stopped-containers
$ROOT/commands/remove-inactive-volumes
$ROOT/commands/remove-untagged-images
