#!/bin/bash

if hash docker-machine 2>/dev/null; then
    eval $(docker-machine env default)
fi

docker pull livingstoneonline/ftp
docker pull livingstoneonline/base
docker pull livingstoneonline/mysql
docker pull livingstoneonline/tomcat
docker pull livingstoneonline/drupal
docker pull livingstoneonline/livingstone:${1:-dev}
