#!/bin/sh
eval $(docker-machine env livingstone)
readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly IP=$(/usr/local/bin/VBoxManage guestproperty enumerate livingstone | grep '/VirtualBox/GuestInfo/Net/1/V4/IP' | sed -n 's/^.*value: \([0-9\.]*\),.*$/\1/p')
docker exec drupal killall unison
docker exec -d drupal sh -c "(unison -socket 5000 &);"
sleep 3
unison socket://$IP:5000//var/www/localhost/htdocs/sites $DIR/../sites -auto -batch -prefer socket://$IP:5000//var/www/localhost/htdocs/sites
docker exec drupal killall unison
