#!/bin/bash
echo "Docker Compose Up"
eval $(docker-machine env livingstone)
docker-compose pull
docker-compose stop
sleep 20
docker-compose rm -f
sleep 20
docker images | grep none | awk '{ print $3 }' | xargs docker rmi
docker volume ls -q | xargs docker volume rm
docker-compose up -d
exit 0
