#!/bin/bash
echo "Docker Compose Up"
eval $(docker-machine env livingstone)
docker-compose pull
docker-compose stop
docker-compose rm -f
docker images | grep none | awk '{ print $3 }' | xargs docker rmi
docker-compose up -d
exit 0
