#!/bin/bash
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
cd $ROOT
readonly config=$(vagrant ssh-config)
echo "Searching for the IP of the Vagrant Box"
IP=$(/usr/local/bin/VBoxManage guestproperty enumerate livingstone | grep '/VirtualBox/GuestInfo/Net/1/V4/IP' | sed -n 's/^.*value: \([0-9\.]*\),.*$/\1/p')
readonly host=$IP
readonly user=$(echo $config | egrep -o 'User ([-_a-zA-Z0-9]*)' | sed 's/User //')
readonly port=22
readonly identity=$(echo $config | egrep -o 'IdentityFile "(.*)"' | sed 's/^IdentityFile "\(.*\)"$/\1/')

echo "Installing Docker on Vagrant Box"
echo "Host: $host"
echo "User: $user"
echo "Port: $port"
echo "Identity: $identity"
/usr/local/bin/docker-machine create -d generic \
               --generic-ssh-user $user \
               --generic-ssh-key $identity \
               --generic-ssh-port $port \
               --generic-ip-address $host \
               --engine-install-url "https://get.docker.com" \
               livingstone
exit 0
