#!/bin/bash
eval $(docker-machine env livingstone)
readonly IP=$(/usr/local/bin/VBoxManage guestproperty enumerate livingstone | grep '/VirtualBox/GuestInfo/Net/1/V4/IP' | sed -n 's/^.*value: \([0-9\.]*\),.*$/\1/p')

main() {
    if docker run --rm nigelgbanks/base /usr/local/bin/dockerize -wait http://$IP:80 -timeout 15m 1>/dev/null; then
        /usr/bin/osascript -e "open location \"http://$IP\""
    else
        /usr/bin/osascript -e "display alert \"Something has gone wrong! Bug Nigel!\""
    fi
}
main &
